### ISSUE TITLE
Ezt a hiba üzenetet kapom mindig

### ISSUE THREAD

**Issue by EyeDragon2001** [S3nS3IW00/mcserverlauncher#1]
[11:34:24 EXCEPTION]: [Logger] java.lang.IllegalArgumentException: Illegal base64 character a

	at java.util.Base64$Decoder.decode0(Unknown Source)

	at java.util.Base64$Decoder.decode(Unknown Source)

	at java.util.Base64$Decoder.decode(Unknown Source)

	at app.mcsl.manager.file.FileManager.decodeBase64ToImage(FileManager.java:541)

	at app.mcsl.window.element.ServerCard.lambda$updateInfos$12(ServerCard.java:258)

	at app.mcsl.window.element.ServerCard$$Lambda$461/96294421.run(Unknown Source)

	at com.sun.javafx.application.PlatformImpl.lambda$null$170(Unknown Source)

	at com.sun.javafx.application.PlatformImpl$$Lambda$48/835219411.run(Unknown Source)

	at java.security.AccessController.doPrivileged(Native Method)

	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(Unknown Source)

	at com.sun.javafx.application.PlatformImpl$$Lambda$47/1915503092.run(Unknown Source)

	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)

	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)

	at com.sun.glass.ui.win.WinApplication.lambda$null$145(Unknown Source)

	at com.sun.glass.ui.win.WinApplication$$Lambda$36/1963387170.run(Unknown Source)

	at java.lang.Thread.run(Unknown Source)

**Comment by S3nS3IW00** [comment]
Szerver verziója, aminél ezt a hibát kijelzi? Van beállítva logó a szerverhez? Ha igen, akkor a játékban a szerverlistán azt jelzi ki?

**Comment by EyeDragon2001** [comment]
Igen jelzi azt

**Comment by S3nS3IW00** [comment]
Részben javítva. Ugyan nem jeleníti meg a szerver ikonját, viszont most már nem dobja fel a hibát.
